kulupu-lapo/poki

plaintext/2025/04/monsuta-wawa-meli.md, plaintext/2025/04/monsuta-wawa-meli.yaml
=> [submission] from kala Asi: monsuta wawa meli

plaintext/2023/03/tomo-wasinsan.md, plaintext/2023/03/tomo-wasinsan.yaml
=> [submission] from kala Asi: tomo Wasinsan

plaintext/2023/08/meli-pimeja.md
=> [submission] from kala Asi: meli pimeja

plaintext/2025/03/supa-selo.md
=> [submission] from kala Asi: supa selo

plaintext/2023/08/tawa-pi-pakala-wile.md, plaintext/2023/09/tawa-pi-pakala-wile.yaml
=> [submission] from kala Asi: tawa pi pakala wile

plaintext/2025/05/musi-Koton-100.md
=> [submission] from jan Pawasi: musi Koton 100%

collections/nasin-anpa.yaml, collections/nasin-sisuke.yaml, plaintext/2025/05/nasin-anpa-kon-lipu.md, plaintext/2025/05/nasin-anpa-o-olin-tawa-mama-lon-tomo.md
[DiZiGui Ch0-1.pdf](https://github.com/user-attachments/files/20227090/DiZiGui.Ch0-1.pdf)
may want to do a last triple check that I actually transcribed my sitelen pona into sitelen Lasina right lol
=> [submission] from soweli suli Alu pi ko lete: chapters 0-1 of Dizigui translation

plaintext/2024/12/jan-selo-o-li-alasa-sona.md
=> [submission] from jan Tene: jan Selo O li alasa sona

plaintext/2025/04/utala-lili-jan-sepo-27-04-2025.md
=> [submission] from jan Sepo: utala lili

plaintext/2025/05/kasi-li-lon-poka-nasin.md
=> [submission] from kon Okisen: kasi li lon poka nasin

plaintext/2025/04/mi-ken-kama-kulupu-pi-mun-lili-la.md
=> [submission] from jan Pikesike: mi ken kama kulupu pi mun lili la

plaintext/2025/05/mi-weka-la.md
=> [submission] from jan Pikesike: mi weka la

collections/utala-musi/2023-musi-mu.yaml, plaintext/2023/04/esun-pi-jan-suli-ike-pi.md, plaintext/2023/04/jaki-mesotelijoma.md, plaintext/2023/05/ilo-pi-nanpa.md, plaintext/2023/05/lape-pona-jan-kesi-en-jan-atumo.md, plaintext/2023/05/le-kijetesantakalu-lon-mani.md
picking up what #11 excluded, within reason
i deemed "‘mi tawa kepeken nasin pona’ tan jan Simiman" too short to be worth including but i may be wrong, transcription by @jnpoJuwan:
> `ILO NI-1 PI SIKE TU LA MI [sic] ILO PONA`
> `NASIN NI-3 KEPEKEN (jan li kepeken e ilo pi sike tu)`
> 
> ilo pi sike tu la ona li ilo pona
> nasin ni li kepeken [jan li kepeken e ilo pi sike tu]
=> utala pi musi mu

plaintext/2024/02/suno-pi-toki-pona-pi-nanpa-3.md
=> [submission] from kala Asi: suno pi toki pona pi #3

plaintext/2024/06/ilo-tenpo-luka.md
=> [submission] from kala Asi: ilo tenpo luka

plaintext/2023/08/pakala-li-lon-telo-sijelo-loje.md
=> [submission] from kala Asi: pakala li lon telo sijelo loje

plaintext/2025/05/jan-miko-en-jan-lojen-li-moku-e-ko-lete.md
=> [submission] from jan Iwi: jan Miko en jan Lojen li moku e ko lete

plaintext/2024/08/toki-pi-jan-lanto-kate.md
=> [submission] from jan Tene: toki pi jan Lanto Kate

plaintext/2023/09/sina-li-nanpa.md
=> [submission] from jan Kita: sina li nanpa

plaintext/2024/08/kalama-musi-pi-jan-eli-san.md
=> [submission] from jan Tene: kalama musi pi jan Eli San

plaintext/2024/08/kala-sewi-takon.md
=> [submission] from jan Tene: kala sewi Takon

plaintext/2024/08/sitelen-lon-tomo-majuna.md
=> [submission] from jan Tene: sitelen lon tomo majuna

plaintext/2023/02/telo-sewi.md
=> [submission] from soko Kan: telo sewi

plaintext/2023/02/pimeja.md
=> [submission] from soko Kan: pimeja

plaintext/2023/02/sijelo-li-sona-musi.md
=> [submission] from soko Kan: sijelo li sona musi

plaintext/2023/02/tenpo-akesi.md
=> [submission] from soko Kan: tenpo akesi

plaintext/2023/02/kala-sina.md
=> [submission] from soko Kan: kala sina

plaintext/2025/04/jan-gaius-van-baelsar-li-lon-ilo-pi-tawa-anpa-li-toki-mute-tawa-sina.md
=> [submission] from jan Nowenpa: jan Gaius van Baelsar li lon ilo pi tawa anpa li toki mute tawa sina

plaintext/2025/05/jan-olin-pi-kalama-musi.md
=> [submission] from jan Pikesike: jan olin pi kalama musi

plaintext/2023/05/poki-pi-jan-amonsijato.md
Update entry after proofreading by selo Muna and jan Tepo for linja monsuta (2024) (They have to deal with so many bad tp sentences D: )
Should the date be changed to reflect the changes made. I'm not sure so I did not change it.
(also why is the file name "poki pi *jan* Amonsijato" lol, also not changing it so it wont break stuff)
=> Update entry "poki pi telo Amonsijato" to version in linja monsuta

plaintext/2025/01/ijo-055-sona-ala.md
I didn't even notice these before lol. That's what I get for typing in UCSUR and then transcribing into Latin text.
=> Fixed some typos

plaintext/2025/05/tenpo-pi-kule-soweli-lili.md
=> [submission] from jan Pikesike: tenpo pi kule soweli (lili)

plaintext/2025/05/kili-loje.md
=> [submission] from soko Sijeni: kili loje

plaintext/2025/06/jan-lon-ma-nena.md
=> [submission] from jan Pikesike: jan lon ma nena

plaintext/2022/11/lon-pi-jan-pearl-hart.md
=> [submission] from kule epiku Atawan: lon pi jan Pearl Hart

plaintext/2024/03/monsuta-li-moli-e-jan-500m-li-pini.md, plaintext/2025/03/ma-pona-lon-poka-pi-telo-anpa.md
Two blog posts by jan Siwa (that's me).
Originally published at https://blog.purpureus.net/tags/toki-pona/
=> Add two entries from jan Siwa's blog.

plaintext/2025/06/kalama-musi-pi-moku-namako.md
=> [submission] from jan Pikesike: kalama musi pi moku... namako!

plaintext/2025/05/jan-papi.md
=> [submission] from jan Papesike: jan Papi

plaintext/2025/06/jan-pi-lawa-lawa.md
=> [submission] from jan Pikesike: jan pi lawa lawa

plaintext/2025/05/ma-tomo.md
=> [submission] from soko Sijeni: ma tomo

plaintext/2025/06/mumumumumumumu.md
=> [submission] from jan Pikesike: mumumumumumumu!

plaintext/2009/11/jan-lawa-oliki.md, plaintext/2011/03/jan-lawa-oliki.md, plaintext/2022/10/jan-lawa-oliki.md
jan lawa Oliki is an adaptation of a slavic legend put into a poem by Alexander Pushkin.
soweli Elepanto uploaded a translation to the forums in 2009: http://forums.tokipona.org/viewtopic.php?p=5677#p5677
This was reuploaded with minor changes to olukin.blogspot.org in 2011: https://olukin.blogspot.com/2011/04/jan-lawa-oliki.html
jan Pensa then collaborated with soweli Elepanto to make a new revision in 2022, which featured in pu Epelanto: https://wikisource.org/wiki/Jan_lawa_Oliki_(2022)
this PR adds the original revision, and fixes the metadata on the other two to list the correct original source
=> [fix] jan lawa oliki

plaintext/2025/06/mije-sama-mi-li-kama-meli-sama-mi-lipu-lili-nanpa-tu-tu-jan-masilo-en-musi-linluwi-pi-jan-mute-mute.md
=> [submission] from jan Pikesike: mije sama mi li kama meli sama mi! (lipu lili nanpa tu tu: jan Masilo en musi linluwi pi jan mute mute)

plaintext/2025/06/tenpo-pi-ma-pini.md
=> [submission] from kulupu Kasi: tenpo pi ma pini

plaintext/2025/07/mije-sama-mi-li-kama-meli-sama-mi-lipu-lili-nanpa-luka-jan-masilo-en-tenpo-pi-pilin-ike.md
=> [submission] from jan Pikesike: mije sama mi li kama meli sama mi! (lipu lili nanpa luka: jan Masilo en tenpo pi pilin ike)

plaintext/2025/03/pona-len.md
=> [submission] from jan Tene: pona len

collections/fail-blue-dot.yaml, collections/kijetesantakalu-o.yaml, collections/lipu-tenpo.yaml, collections/lipu-tenpo/0032-nanpa-supa.yaml, collections/seme-li-mi.yaml, plaintext/2013/01/jan-lawa-lili.md, plaintext/2025/03/pona-len.md, plaintext/2025/06/alasa-pakala.md, plaintext/2025/06/esun-supa.md, plaintext/2025/06/jan-kasi-en-nasin-kasi.md, plaintext/2025/06/kijetesantakalu-o.md, plaintext/2025/06/lon-telo-pi-waso-mute.md, plaintext/2025/06/mi-jan-seme.md, plaintext/2025/06/mun-li-jo-e-lupa-sike-tan-seme.md, plaintext/2025/06/musi-li-ken-kama-tan-pali.md, plaintext/2025/06/musi-pi-utala-telo.md, plaintext/2025/06/pilin-sama.md, plaintext/2025/06/seme-li-mi.md, plaintext/2025/06/seme-telo-li-supa-ala.md, plaintext/2025/06/soko-li-seme.md, plaintext/2025/06/supa-pi-toki-ante.md, plaintext/2025/06/tenpo-lon-ma-ante.md
=> [submission] from jan Tene: jan lawa lili

plaintext/2022/07/sona-sin-pona-tan-jan-sewi-jojane.md
=> [submission] from jan Tene: sona sin pona tan jan sewi Jojane

plaintext/2025/07/mije-sama-mi-li-kama-meli-sama-mi-lipu-lili-nanpa-luka-wan-jan-masilo-en-ma-len.md
=> [submission] from jan Pikesike: mije sama mi li kama meli sama mi! (lipu lili nanpa luka wan: jan Masilo en ma len)

plaintext/2025/07/mije-sama-mi-li-kama-meli-sama-mi-lipu-lili-nanpa-luka-tu-jan-masilo-en-jan-pi-sona-ala-ona.md
=> [submission] from jan Pikesike: mije sama mi li kama meli sama mi! (lipu lili nanpa luka tu: jan Masilo en jan pi sona ala ona)

plaintext/2025/07/jan-pasi-oli.md
=> [submission] from jan Pikesike: jan Pasi Oli

plaintext/2025/08/mi-o-pali-lon-tenpo-sike-kama.md
=> [submission] from jan Awa: "mi o pali lon tenpo sike kama"

plaintext/2025/06/jan-misikeke.md
=> [submission] from jan Lisente: jan misikeke

plaintext/2025/09/jan-pawe-en-jan-kawe.md
=> [submission] from jan Esuwa: jan Pawe en jan Kawe

plaintext/2025/09/ilo-kalama-linja-en-pilin-pi-wan-taso-en-ma-laso-nanpa-tu.md
=> [submission] from jan Pikesike: ilo kalama linja en pilin pi wan taso en ma laso (nanpa tu)

plaintext/2025/09/mi-ken-kama-kulupu-pi-mun-lili-la-nanpa-tu-wan.md
=> [submission] from jan Pikesike: mi ken kama kulupu pi mun lili la (nanpa tu wan)

collections/soko-sijeni/jan-kisote.yaml, collections/soko-sijeni/ma-suno.yaml, collections/soko-sijeni/soko-sijeni.yaml, plaintext/2025/02/tawa-pona.md, plaintext/2025/04/open-utala.md, plaintext/2025/04/tawa-nanpa-wan-pi-jan-kisote.md, plaintext/2025/08/olin-mama.md, plaintext/2025/08/pona-sama.md, plaintext/2025/08/soko-lili.md, plaintext/2025/09/lawa-li-jan-utala-e-jan-kisote.md
This again.
New works:
* pona sama
* soko lili
* lawa li jan utala e jan Kisote
Others:
* I changed the format of footnotes in my site so I tried to change it here too with inline notes
* I changed all of the names in my 'ma suno' series for reasons
* I put line breaks in 'tawa pona' that were missing
=> soko Sijeni- all new works and updates
